In [1]:
import pandas as pd

In [ ]:
df = pd.read_excel(r"File_Location")

In [5]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [6]:
df.isnull().mean()*100

InvoiceNo       0.000000
StockCode       0.000000
Description     0.268311
Quantity        0.000000
InvoiceDate     0.000000
UnitPrice       0.000000
CustomerID     24.926694
Country         0.000000
dtype: float64

In [11]:
df[df['UnitPrice'] < 0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom

In [12]:
df[df['UnitPrice'] < 0].shape

(2, 8)

In [ ]:
### Negative Unit Prices

Two records contain negative `UnitPrice` values. Both are described as `Adjust bad debt` and have no `CustomerID`, indicating that they are accounting adjustments rather than normal product transactions.

These records will be excluded from the cleaned sales dataset because the project focuses on retail sales transactions.

In [13]:
df = df[df['UnitPrice'] >= 0].copy()

In [14]:
df.shape

(541907, 8)

In [15]:
df[df['Quantity'] < 0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom

In [16]:
df[df['Quantity'] < 0]['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

In [17]:
df[df['Quantity'] < 0].shape

(10624, 8)

In [18]:
df[df['Quantity'] < 0]['InvoiceNo'].astype(str).str.startswith('C').value_counts()

InvoiceNo
True     9288
False    1336
Name: count, dtype: int64

In [19]:
df[(df['Quantity'] < 0) & (~df['InvoiceNo'].astype(str).str.startswith('C'))].head(20)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [20]:
df.duplicated().sum()

np.int64(5268)

In [21]:
df = df.drop_duplicates().copy()

In [22]:
df.shape

(536639, 8)

In [23]:
df = df.dropna(subset=['CustomerID']).copy()

In [24]:
df = df.dropna(subset=['Description']).copy()

In [25]:
df.reset_index(drop=True, inplace=True)

In [26]:
df.shape

(401604, 8)

In [ ]:
df.to_excel("online_retail_cleaned.xlsx", index=False)