In [1]:
import pandas as pd

In [ ]:

df = pd.read_excel(r"file_location\online_retail_cleaned.xlsx")

In [3]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom

In [4]:
df['Revenue'] = df['Quantity'] * df['UnitPrice']

In [5]:
df[['Quantity', 'UnitPrice', 'Revenue']].head()

   Quantity  UnitPrice  Revenue
0         6       2.55    15.30
1         6       3.39    20.34
2         8       2.75    22.00
3         6       3.39    20.34
4         6       3.39    20.34

In [6]:
df['Revenue'].sum()

np.float64(8278519.424)

In [7]:
df['InvoiceDate'].min(), df['InvoiceDate'].max()

(Timestamp('2010-12-01 08:26:00'), Timestamp('2011-12-09 12:50:00'))

In [11]:
df['Month'] = df['InvoiceDate'].dt.to_period('M')

In [12]:
#Monthly Revenue Analysis
monthly_revenue = df.groupby('Month')['Revenue'].sum()

In [13]:
monthly_revenue

Month
2010-12     552372.860
2011-01     473731.900
2011-02     435534.070
2011-03     578576.210
2011-04     425222.671
2011-05     647011.670
2011-06     606862.520
2011-07     573112.321
2011-08     615078.090
2011-09     929356.232
2011-10     973306.380
2011-11    1126815.070
2011-12     341539.430
Freq: M, Name: Revenue, dtype: float64

In [14]:
#Monthly Quantity Analysis
monthly_quantity = df.groupby('Month')['Quantity'].sum()
monthly_quantity

Month
2010-12    295177
2011-01    268755
2011-02    262243
2011-03    343095
2011-04    277730
2011-05    367115
2011-06    356239
2011-07    361359
2011-08    385865
2011-09    536350
2011-10    568898
2011-11    666813
2011-12    203212
Freq: M, Name: Quantity, dtype: int64

In [15]:
#Top Revenue-Generating Products
top_products = df.groupby('Description')['Revenue'].sum().sort_values(ascending=False).head(10)
top_products

Description
REGENCY CAKESTAND 3 TIER              132567.70
WHITE HANGING HEART T-LIGHT HOLDER     93767.80
JUMBO BAG RED RETROSPOT                83056.52
PARTY BUNTING                          67628.43
POSTAGE                                66710.24
ASSORTED COLOUR BIRD ORNAMENT          56331.91
RABBIT NIGHT LIGHT                     51042.84
CHILLI LIGHTS                          45915.41
PAPER CHAIN KIT 50'S CHRISTMAS         41423.78
PICNIC BASKET WICKER 60 PIECES         39619.50
Name: Revenue, dtype: float64